### ISSUE TITLE
Aligning depth and color images

### ISSUE THREAD

**Issue by vinkle** [CMU-Perceptual-Computing-Lab/panoptic-toolbox#11]
Hey folks, Thanks for the great work!
I am trying to align the Kinect depth and color images using the intrinsic of color and depth camera. So far, I have not been successful. It generates the misaligned color and depth images. Please see the Matlab script for the alignment and the generated images. It would be very helpful if you can help me to resolve the issue. 
 
![color](https://user-images.githubusercontent.com/722672/48546706-506a1480-e8c9-11e8-8c20-322f21065cd2.jpg)
![depth](https://user-images.githubusercontent.com/722672/48546707-506a1480-e8c9-11e8-8265-154d5bee123f.jpg)
![fused](https://user-images.githubusercontent.com/722672/48546709-506a1480-e8c9-11e8-8919-9a93361894bd.jpg)

[align_kineoptic.zip](https://github.com/CMU-Perceptual-Computing-Lab/panoptic-toolbox/files/2584798/align_kineoptic.zip)

**Comment by jhugestar** [comment]
Hi, 

I am wondering whether it was successful when you try your current code for another example dataset (e.g, 171204_pose1)?

**Comment by vinkle** [comment]
Hi, apparently the misalignment issue is also in the "171204_pose1" sequence. Please see the resultant images.
![color](https://user-images.githubusercontent.com/722672/48765318-3312bd00-ecb2-11e8-8381-84d09fcca0e0.jpg)
![depth](https://user-images.githubusercontent.com/722672/48765319-3312bd00-ecb2-11e8-9d54-5740b375a79d.jpg)
![fused](https://user-images.githubusercontent.com/722672/48765320-3312bd00-ecb2-11e8-8b51-bfc1a8971707.jpg)

**Comment by jhugestar** [comment]
Well, then I think it is a bit weird, since I have checked this sequence before releasing it. 
There exists some amount of misalignment due to the occluded region, but I remember the quality was better than this output. 

Are you using our toolbox code? Our pt cloud generation does a similar process to extract RGB color for each 3D points, although it doesn't explicitly make a warped depth (or RGB) image to overlay them. 

I have very briefly checked your code (sorry, due to my time limit), and it seems like you are not using extrinsic parameters, then how did you generate the warped image (e.g., depth img -> 3D pt -> RGB space)? It seems like the misalignment of your output is similar to the amount of view changes between rgb and depth, and this would be the issue. Can you double check this? You may check our toolbox code regarding the extrinsic part (calib.R and calib.t).

**Comment by vinkle** [comment]
Hi, I checked the code, and I missed to apply the extrinsic parameters. Thanks for your help.

**Comment by ashwinvaswani** [comment]
Hi @vinkle, Could you provide your updated code after applying the extrinsic parameters?
