### ISSUE TITLE
Script returns "404 Not Found" when trying to download annotation

### ISSUE THREAD

**Issue by jeffffffli** [CMU-Perceptual-Computing-Lab/panoptic-toolbox#17]
Many sequences like '160224_ultimatum1', '160224_ultimatum2' cannot be downloaded.

I also use URLs in the web browser and still return 404 error. For example:
[http://domedb.perception.cs.cmu.edu/webdata/dataset/160224_ultimatum2/hdFace3d.tar]()
[http://domedb.perception.cs.cmu.edu/webdata/dataset/160224_ultimatum2/hdFace3d.tar]()
[http://domedb.perception.cs.cmu.edu/webdata/dataset/160224_mafia2/hdPose3d_stage1_coco19.tar]()

**Comment by NiteshBharadwaj** [comment]
Same issue on my end. http://domedb.perception.cs.cmu.edu/webdata/dataset/160422_mafia2/hdPose3d_stage1_coco19.tar
is 404
To the poster above, if you have this file, do share

**Comment by jeffffffli** [comment]
Hi, @NiteshBharadwaj . I found that we can download the `joints15` data by replacing `hdPose3d_stage1_coco19.tar` with `hdPose3d_stage1.tar`.
For example, you can use the link [http://domedb.perception.cs.cmu.edu/webdata/dataset/160422_mafia2/hdPose3d_stage1.tar](http://domedb.perception.cs.cmu.edu/webdata/dataset/160422_mafia2/hdPose3d_stage1.tar)

**Comment by jhugestar** [comment]
Hi all, 
There are some missing data (e.g., faces) for old sequences, but we plan to keep updating them (since our algorithm is getting improved). It will not be so quick, but at least within a couple of months. Yes, for some sequences, we still have the old skeleton files ("joints15" with MPI db format) but they are depreciated and not supported anymore. Will keep you updated in this thread.
