### ISSUE TITLE
Segmentation of Point clouds

### ISSUE THREAD

**Issue by ryohachiuma** [CMU-Perceptual-Computing-Lab/panoptic-toolbox#19]
Hi, thanks for providing awesome dataset and code!

I have a question about Figure. 11 in the paper. 
(https://arxiv.org/abs/1612.03153)
At row 2 of Figure 11, the merged point cloud is segmented into body parts. Is there any code to reproduce the segmentation? 

Thanks for considering in advance!

**Comment by jhugestar** [comment]
OK, that paper is very early one (before the Deep Learning based pose detector e.g., OpenPose), and we were using DPM. The pt cloud segmentation (pt cloud was from SIFT matching, since we didn't have kinects!!) was intended to filter out very noisy 2D detection output (and code is way too complicated to be shared). 

Given the fact that now we are already given pretty good skeletons and pt clouds (from Kinects), you can simply apply Euclidean distance based thresholding to make such segmentation. For example, given a 3D point, just find the closest skeletons and determine its membership. There are couple of issues in pursuing this (for example, torso should have larger volume than limbs), but this can be a good start point. 

Note that if motions are too fast PT clouds from Kinects are not synchronized with 3D skeletons. 

You may check recent paper from Hyun Soo's group with the similar goal: https://www-users.cs.umn.edu/~jsyoon/Semantic_trajectory/
